#include "truand.h"

static int tru15(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return a;
}

static int tru14(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru15(a);
}

static int tru13(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru14(a);
}

static int tru12(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru13(a);
}

static int tru11(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru12(a);
}

static int tru10(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru11(a);
}

static int tru9(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru10(a);
}

static int tru8(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru9(a);
}

static int tru7(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru8(a);
}

static int tru6(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru7(a);
}

static int tru5(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru6(a);
}

static int tru4(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru5(a);
}

static int tru3(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru4(a);
}

static int tru2(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru3(a);
}

static int tru1(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru2(a);
}

int truand(int a)
{
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    a = a + 1;
    a = a - 1;
    return tru1(a);
}
